server:
  port: 8124

spring:
  profiles:
    active: dev

##数据源配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/push_mate?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: root
#  type: com.alibaba.druid.pool.DruidDataSource
#  druid:
#    #初始化连接大小
#    initial-size: 5
#    #最小连接池数量
#    min-idle: 5
#    #最大连接池数量
#    max-active: 20
#    #获取连接时最大等待时间，单位毫秒
#    max-wait: 60000
#    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    time-between-eviction-runs-millis: 60000
#    #配置一个连接在池中最小生存的时间，单位是毫秒
#    min-evictable-idle-time-millis: 300000
#    #测试连接
#    validationQuery: SELECT 1 from DUAL
#    #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
#    testWhileIdle: true
#    #获取连接时执行检测，建议关闭，影响性能
#    testOnBorrow: false
#    #归还连接时执行检测，建议关闭，影响性能
#    testOnReturn: false
#    #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
#    poolPreparedStatements: false
#    #开启poolPreparedStatements后生效
#    maxPoolPreparedStatementPerConnectionSize: 20
#    #配置扩展插件，常用的插件有=>stat:监控统计  slf4j:日志  wall:防御sql注入
#    filters: wall,stat
